baseurl = "https://federicotorrielli.github.io/blog"
title = "Federico Torrielli - Blog"
author = "Federico Torrielli"
canonifyurls = true
languagecode = "en-us"
theme = "hugo-black-and-light-theme"

enableEmoji = true
hasCJKLanguage = false

pygmentsstyle = "bw"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
  sitename = "Federico Torrielli - Blog"
  highlightjs = true
  highlightjslanguages = ["python3", "stan", "bash"]
  uselatex = true
  disableWebFonts = false
  progressively = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.goldmark.extensions]
    [markup.goldmark.extensions.passthrough]
      enable = true
      [markup.goldmark.extensions.passthrough.delimiters]
        block = [['$$', '$$']]
        inline = [['$', '$']]

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/federicotorrielli"
    weight = 2
[[menu.main]]
    name = "Website"
    url = "https://evilscript.eu"
    weight = 3

